/**
 * Export utilities for generating PDF reports, JSON downloads, and clipboard copies.
 */

/**
 * Copies the maintenance ticket details in text format to the user's clipboard.
 */
export const copyTicketDetails = (ticket) => {
  const text = `
===========================================================
MAINTENANCE WORK ORDER: ${ticket.ticketId}
===========================================================
Created At:          ${ticket.timestamp}
Ticket Status:       ${ticket.status}
Priority Level:      ${ticket.priority}
Assigned Engineer:   ${ticket.assignedEngineer}

-----------------------------------------------------------
1. ASSET SPECIFICATION
-----------------------------------------------------------
Engine Model:        TJ-900 TURBOJET TWIN
Target Subsystem:    ${ticket.asset.component}
Simulation Profile:  ${ticket.asset.profile}

-----------------------------------------------------------
2. RUNTIME TELEMETRY SNAPSHOT
-----------------------------------------------------------
Altitude:            ${ticket.asset.telemetry.Altitude}
Mach Speed:          ${ticket.asset.telemetry.MachSpeed}
Rotor Core Speed:    ${ticket.asset.telemetry.RotorRPM}
Fuel Flow Rate:      ${ticket.asset.telemetry.FuelFlow}
Ambient Temperature: ${ticket.asset.telemetry.AmbientTemp}
Ambient Pressure:    ${ticket.asset.telemetry.AmbientPressure}
Pressure Ratio:      ${ticket.asset.telemetry.CPR} : 1
Compressor In Temp:  ${ticket.asset.telemetry.T2}
Combustor In Temp:   ${ticket.asset.telemetry.T3}
Exhaust Gas Temp:    ${ticket.asset.telemetry.T4}

-----------------------------------------------------------
3. LSTM SURROGATE HEALTH DIAGNOSTICS
-----------------------------------------------------------
Compressor Health:   ${ticket.predictions.compressorHealth} ${ticket.predictions.compressorHealthUncertainty || ''}
Combustor Health:    ${ticket.predictions.combustorHealth} ${ticket.predictions.combustorHealthUncertainty || ''}
Turbine Health:      ${ticket.predictions.turbineHealth} ${ticket.predictions.turbineHealthUncertainty || ''}
Overall Core Health: ${ticket.predictions.overallHealth} ${ticket.predictions.overallHealthUncertainty || ''}
Thrust Output:       ${ticket.predictions.thrust} ${ticket.predictions.thrustUncertainty || ''}
TSFC Index:          ${ticket.predictions.tsfc} ${ticket.predictions.tsfcUncertainty || ''}

-----------------------------------------------------------
4. AI EXPERT DIAGNOSTIC ADVISORY
-----------------------------------------------------------
Threat Severity:     ${ticket.aiDiagnosis.severity}
Diagnosis Heading:   ${ticket.aiDiagnosis.title}
Condition Summary:   ${ticket.aiDiagnosis.summary}
Recommendation:      ${ticket.aiDiagnosis.recommendation}

-----------------------------------------------------------
5. WORK ORDER COMMAND DISPATCH
-----------------------------------------------------------
Required Action:     ${ticket.suggestedAction}

===========================================================
Generated by AI Digital Twin Predictive Maintenance System.
`;
  return navigator.clipboard.writeText(text.trim());
};

/**
 * Downloads the maintenance ticket as a formatted JSON file.
 */
export const downloadTicketJSON = (ticket) => {
  const jsonStr = JSON.stringify(ticket, null, 2);
  const blob = new Blob([jsonStr], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `maintenance_ticket_${ticket.ticketId}.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

/**
 * Generates a clean, professional, printable PDF document inside a print window.
 */
export const exportInspectionReportPDF = (ticket) => {
  const severity = ticket.aiDiagnosis.severity;
  
  // Decide severity styling colors for printing
  let sevColor = "#10b981"; // emerald
  let sevBg = "#ecfdf5";
  if (severity.toLowerCase().includes("critical")) {
    sevColor = "#f43f5e"; // rose
    sevBg = "#fff1f2";
  } else if (severity.toLowerCase().includes("warning")) {
    sevColor = "#f59e0b"; // amber
    sevBg = "#fffbeb";
  } else if (severity.toLowerCase().includes("advisory")) {
    sevColor = "#a78bfa"; // purple
    sevBg = "#f5f3ff";
  }

  // Create document layout with embedded print-friendly styles
  const htmlContent = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>Inspection Report - ${ticket.ticketId}</title>
      <style>
        body {
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
          color: #1e293b;
          margin: 0;
          padding: 40px;
          line-height: 1.5;
          background: #ffffff;
        }
        
        .report-header {
          border-bottom: 3px double #0f172a;
          padding-bottom: 20px;
          margin-bottom: 30px;
          display: flex;
          justify-content: space-between;
          align-items: flex-end;
        }

        .header-left h1 {
          font-size: 24px;
          font-weight: 800;
          margin: 0;
          color: #0f172a;
          text-transform: uppercase;
          letter-spacing: 0.5px;
        }
        
        .header-left p {
          font-size: 13px;
          color: #64748b;
          margin: 4px 0 0 0;
        }

        .header-right {
          text-align: right;
        }

        .session-id {
          font-family: monospace;
          background: #f1f5f9;
          padding: 3px 8px;
          border-radius: 4px;
          font-size: 11px;
          color: #475569;
        }

        .grid-two-col {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 30px;
          margin-bottom: 30px;
        }

        .info-card {
          border: 1px solid #e2e8f0;
          border-radius: 8px;
          padding: 16px;
          background: #fafafa;
        }

        .info-card h3 {
          margin: 0 0 12px 0;
          font-size: 14px;
          color: #0f172a;
          text-transform: uppercase;
          border-bottom: 1px solid #e2e8f0;
          padding-bottom: 6px;
        }

        .data-table {
          width: 100%;
          border-collapse: collapse;
          font-size: 13px;
        }

        .data-table td {
          padding: 6px 0;
          border-bottom: 1px dashed #e2e8f0;
        }

        .data-table tr:last-child td {
          border-bottom: none;
        }

        .data-table .label {
          color: #64748b;
        }

        .data-table .value {
          font-weight: 600;
          text-align: right;
          color: #0f172a;
        }

        .ai-brief {
          border: 1px solid #e2e8f0;
          border-radius: 8px;
          margin-bottom: 30px;
          overflow: hidden;
        }

        .ai-brief-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          background: #f8fafc;
          padding: 12px 16px;
          border-bottom: 1px solid #e2e8f0;
        }

        .ai-brief-header h3 {
          margin: 0;
          font-size: 14px;
          color: #0f172a;
          text-transform: uppercase;
        }

        .badge {
          background: ${sevBg};
          color: ${sevColor};
          border: 1px solid ${sevColor}30;
          font-size: 11px;
          font-weight: 700;
          text-transform: uppercase;
          padding: 2px 8px;
          border-radius: 4px;
        }

        .ai-brief-body {
          padding: 16px;
        }

        .ai-brief-body h4 {
          margin: 0 0 8px 0;
          font-size: 15px;
          color: #0f172a;
        }

        .ai-brief-body p {
          margin: 0 0 16px 0;
          font-size: 13px;
          color: #334155;
          line-height: 1.6;
        }

        .rec-block {
          background: #f8fafc;
          border-left: 4px solid ${sevColor};
          padding: 12px 16px;
          border-radius: 0 6px 6px 0;
        }

        .rec-block span {
          display: block;
          font-size: 11px;
          font-weight: 700;
          color: #64748b;
          text-transform: uppercase;
          margin-bottom: 4px;
        }

        .rec-block p {
          margin: 0;
          font-size: 13px;
          font-style: italic;
          color: #334155;
        }

        .health-bar-container {
          display: flex;
          align-items: center;
          gap: 10px;
          margin-top: 4px;
        }

        .health-bar-track {
          flex: 1;
          height: 6px;
          background: #e2e8f0;
          border-radius: 3px;
          overflow: hidden;
        }

        .health-bar-fill {
          height: 100%;
          background: #10b981;
        }

        .summary-box {
          border: 2px solid #0f172a;
          border-radius: 8px;
          padding: 20px;
          background: #f8fafc;
          margin-bottom: 40px;
        }

        .summary-box h3 {
          margin: 0 0 10px 0;
          font-size: 15px;
          color: #0f172a;
          text-transform: uppercase;
        }

        .summary-box p {
          margin: 0 0 15px 0;
          font-size: 13.5px;
          color: #334155;
          line-height: 1.6;
        }

        .footer {
          border-top: 1px solid #cbd5e1;
          padding-top: 16px;
          margin-top: 50px;
          display: flex;
          justify-content: space-between;
          font-size: 11px;
          color: #94a3b8;
        }

        @media print {
          body {
            padding: 20px;
          }
          button {
            display: none;
          }
        }
      </style>
    </head>
    <body>
      <div class="report-header">
        <div class="header-left">
          <h1>Turbojet Inspection Report</h1>
          <p>Predictive Diagnostics Outages & Structural Analysis</p>
        </div>
        <div class="header-right">
          <span class="session-id">TICKET LINK ID: ${ticket.ticketId}</span>
          <p style="margin: 6px 0 0 0; font-size: 12px; color: #64748b;">Date: ${ticket.timestamp}</p>
        </div>
      </div>

      <div class="grid-two-col">
        <!-- Engine & Run Metadata -->
        <div class="info-card">
          <h3>Asset Information</h3>
          <table class="data-table">
            <tr>
              <td class="label">Engine Model</td>
              <td class="value">TJ-900 DIGITAL TWIN</td>
            </tr>
            <tr>
              <td class="label">Target Subsystem</td>
              <td class="value">${ticket.asset.component}</td>
            </tr>
            <tr>
              <td class="label">Simulation Profile</td>
              <td class="value">${ticket.asset.profile}</td>
            </tr>
            <tr>
              <td class="label">Operational Status</td>
              <td class="value" style="color: ${sevColor};">${ticket.aiDiagnosis.severity}</td>
            </tr>
          </table>
        </div>

        <!-- Telemetry snapshot -->
        <div class="info-card">
          <h3>Operational Conditions</h3>
          <table class="data-table">
            <tr>
              <td class="label">Altitude / Mach</td>
              <td class="value">${ticket.asset.telemetry.Altitude} @ ${ticket.asset.telemetry.MachSpeed}</td>
            </tr>
            <tr>
              <td class="label">Rotor Speed (RPM)</td>
              <td class="value">${ticket.asset.telemetry.RotorRPM}</td>
            </tr>
            <tr>
              <td class="label">Fuel Flow Rate</td>
              <td class="value">${ticket.asset.telemetry.FuelFlow}</td>
            </tr>
            <tr>
              <td class="label">Pressure Ratio (CPR)</td>
              <td class="value">${ticket.asset.telemetry.CPR} : 1</td>
            </tr>
          </table>
        </div>
      </div>

      <div class="grid-two-col">
        <!-- Core Prognostics -->
        <div class="info-card" style="grid-column: span 2;">
          <h3>Surrogate LSTM Forecast Model</h3>
          <table class="data-table">
            <tr>
              <td class="label" style="width: 30%;">Compressor Health</td>
              <td class="value" style="width: 25%;">${ticket.predictions.compressorHealth} <span style="font-size: 0.8em; color: #6b7280; font-weight: normal;">${ticket.predictions.compressorHealthUncertainty || ''}</span></td>
              <td>
                <div class="health-bar-container">
                  <div class="health-bar-track">
                    <div class="health-bar-fill" style="width: ${ticket.predictions.compressorHealth}; background: ${parseFloat(ticket.predictions.compressorHealth) >= 95 ? '#10b981' : parseFloat(ticket.predictions.compressorHealth) >= 85 ? '#f59e0b' : '#f43f5e'};"></div>
                  </div>
                </div>
              </td>
            </tr>
            <tr>
              <td class="label">Combustor Health</td>
              <td class="value">${ticket.predictions.combustorHealth} <span style="font-size: 0.8em; color: #6b7280; font-weight: normal;">${ticket.predictions.combustorHealthUncertainty || ''}</span></td>
              <td>
                <div class="health-bar-container">
                  <div class="health-bar-track">
                    <div class="health-bar-fill" style="width: ${ticket.predictions.combustorHealth}; background: ${parseFloat(ticket.predictions.combustorHealth) >= 95 ? '#10b981' : parseFloat(ticket.predictions.combustorHealth) >= 85 ? '#f59e0b' : '#f43f5e'};"></div>
                  </div>
                </div>
              </td>
            </tr>
            <tr>
              <td class="label">Turbine Health</td>
              <td class="value">${ticket.predictions.turbineHealth} <span style="font-size: 0.8em; color: #6b7280; font-weight: normal;">${ticket.predictions.turbineHealthUncertainty || ''}</span></td>
              <td>
                <div class="health-bar-container">
                  <div class="health-bar-track">
                    <div class="health-bar-fill" style="width: ${ticket.predictions.turbineHealth}; background: ${parseFloat(ticket.predictions.turbineHealth) >= 95 ? '#10b981' : parseFloat(ticket.predictions.turbineHealth) >= 85 ? '#f59e0b' : '#f43f5e'};"></div>
                  </div>
                </div>
              </td>
            </tr>
            <tr>
              <td class="label">Overall Core Health</td>
              <td class="value">${ticket.predictions.overallHealth} <span style="font-size: 0.8em; color: #6b7280; font-weight: normal;">${ticket.predictions.overallHealthUncertainty || ''}</span></td>
              <td>
                <div class="health-bar-container">
                  <div class="health-bar-track">
                    <div class="health-bar-fill" style="width: ${ticket.predictions.overallHealth}; background: ${parseFloat(ticket.predictions.overallHealth) >= 95 ? '#10b981' : parseFloat(ticket.predictions.overallHealth) >= 85 ? '#f59e0b' : '#f43f5e'};"></div>
                  </div>
                </div>
              </td>
            </tr>
            <tr>
              <td class="label">Thrust Force Output</td>
              <td class="value" colspan="2" style="text-align: left; padding-left: 20px;">${ticket.predictions.thrust} <span style="font-size: 0.8em; color: #6b7280; font-weight: normal;">${ticket.predictions.thrustUncertainty || ''}</span></td>
            </tr>
            <tr>
              <td class="label">TSFC Metric</td>
              <td class="value" colspan="2" style="text-align: left; padding-left: 20px;">${ticket.predictions.tsfc} <span style="font-size: 0.8em; color: #6b7280; font-weight: normal;">${ticket.predictions.tsfcUncertainty || ''}</span></td>
            </tr>
          </table>
        </div>
      </div>

      <!-- AI Expert Advisory Brief -->
      <div class="ai-brief">
        <div class="ai-brief-header">
          <h3>AI Diagnostic Advisory</h3>
          <span class="badge">${ticket.aiDiagnosis.severity}</span>
        </div>
        <div class="ai-brief-body">
          <h4>${ticket.aiDiagnosis.title}</h4>
          <p>${ticket.aiDiagnosis.summary}</p>
          <div class="rec-block">
            <span>Actionable Recommendation</span>
            <p>${ticket.aiDiagnosis.recommendation}</p>
          </div>
        </div>
      </div>

      <!-- Outages Action Summary -->
      <div class="summary-box">
        <h3>Inspection Executive Summary</h3>
        <p>
          Structural integrity analysis of the <strong>${ticket.asset.component}</strong> indicates that the subcomponents are operating with health scores matching the predicted overall core index of <strong>${ticket.predictions.overallHealth}</strong>.
          The AI inference model reports a diagnostic severity of <strong>${ticket.aiDiagnosis.severity.toUpperCase()}</strong>.
        </p>
        <div class="rec-block" style="border-left-color: #0f172a; background: #ffffff;">
          <span>Work Dispatch Order Action</span>
          <p style="font-weight: bold; font-style: normal; color: #0f172a;">${ticket.suggestedAction}</p>
        </div>
      </div>

      <div class="footer">
        <span>Generated by AI Digital Twin Predictive Maintenance System // TJ-900</span>
        <span>Timestamp: ${ticket.timestamp}</span>
        <span>Version: DT-v1.2.0</span>
      </div>

      <script>
        // Trigger browser print dialog immediately on render
        window.onload = function() {
          window.print();
        };
      </script>
    </body>
    </html>
  `;

  // Open iframe-based printable window
  const printWindow = window.open("", "_blank");
  if (printWindow) {
    printWindow.document.write(htmlContent);
    printWindow.document.close();
  } else {
    alert("Popup blocker prevented launching the print window. Please allow popups for this dashboard.");
  }
};
